// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations", //no define el contenido de las migrations ni las genera, sino que solo le dice a Prisma dónde guardar los archivos de las migraciones cuando ejecutas: yarn prisma migrate dev --name init
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
